version: '3.8'

services:
  vapory_povray_renderer:
    image: jmaxwilson/povray
    container_name: vapory_povray_renderer
    volumes:
      - ${POVRAY_INPUT_FILE}:/images/input.pov  # Monte le fichier d'entrée
      - ${POVRAY_RESOURCES}:/resources  # Monte le répertoire des ressources
      - ~/images:/images  # Répertoire des images en sortie
    working_dir: /images
    environment:
      POVRAY_WIDTH: "${POVRAY_WIDTH:-1920}"      # Largeur par défaut
      POVRAY_HEIGHT: "${POVRAY_HEIGHT:-1080}"    # Hauteur par défaut
      POVRAY_EXTRA_PARAMS: "${POVRAY_EXTRA_PARAMS:-}"  # Paramètres supplémentaires
    command: >
      +Iinput.pov
      +Ooutput.png
      +W${POVRAY_WIDTH}
      +H${POVRAY_HEIGHT}
      ${POVRAY_EXTRA_PARAMS}
